################################
# The observation types are:
# ANALOGY, COMPARATIVE, DESCRIPTIVE, FACTUAL, INFERENCE
# ##############################

debug: false
expiration-days: 7
mysql:
  host: localhost
  port: 3306
  database: minecraft
  username: user
  password: pass

template-gui:
  filler-item: white_stained_glass_pane
  inventory-name: "&lChoose an observation type!"
  rows: 4
  cancel:
    item: barrier
    position: 31
    name: "&cCancel"

templates:
  ANALOGY:
    gui:
      item: green_concrete
      position: 9
      name: '&aAnalogy'
      lore:
        - '&fComparing natural phenomena with another similar structure or object.'
        - '&fAn advanced form of comparative.'
        - ''
        - '&7Example:'
        - '  &f&oThe trees are line the ones in real-life'
    prompts:
    - prompt: The {} is/are like {}.
      worlds:
        world:
          0:
          - trees
          - clouds
          - mountains
          1:
          - the ones in real-life
          - squares
          - something split (oreo?)
  COMPARATIVE:
    gui:
      item: blue_concrete
      position: 11
      name: '&bComparative'
      lore:
        - '&fComparing one natural phenomena to another; expectations are violated.'
        - ''
        - '&7Example:'
        - '  &f&oThe grass is different from Earth.'
    prompts:
    - prompt: The {} is {}.
      worlds:
        world:
          0:
          - grass
          - trees
          - moon
          1:
          - different from Earth
          - taller than ones on Earth
          - different colored than Earth
  DESCRIPTIVE:
    gui:
      item: orange_concrete
      position: 13
      name: '&6Descriptive'
      lore:
        - '&fRelated to color, temperature, quantity, and other physical attributes.'
        - ''
        - '&7Example:'
        - '  &f&o There are lots of trees.'
    prompts:
    - prompt: There are lots of {}.
      worlds:
        world:
          0:
          - coral
          - trees
    - prompt: There are no {}.
      worlds:
        world:
          0:
          - animals
          - plants
    - prompt: It is really {}.
      worlds:
        world:
          0:
          - hot
          - cold
    - prompt: The {} is {}.
      worlds:
        world:
          0:
          - moon
          - water level
          1:
          - large
          - missing
          - low
          - high
  FACTUAL:
    gui:
      item: purple_concrete
      position: 15
      name: '&9Factual'
      lore:
        - '&fNoun statements without elaborations.'
        - ''
        - '&7Example:'
        - '  &f&oThere are animals.'
    description: Noun statements without elaborations.
    prompts:
    - prompt: There is/are {}.
      worlds:
        world:
          0:
          - animals
          - vegetables
          - mountains
  INFERENCE:
    gui:
      item: pink_concrete
      position: 17
      name: '&dInference'
      lore:
        - '&fA hypothesis or explanation is proposed.'
        - ''
        - '&7Example:'
        - '  &f&oThe plants grow because the sun provides nutrients.'
    prompts:
    - prompt: The {} because {}.
      worlds:
        world:
          0:
          - plants grow
          - is no plant life
          1:
          - the sun provides nutrients
          - the temperatures are too cold to sustain life