name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Jack Henhapl
api-version: 1.13
main: edu.whimc.observationdisplayer.ObservationDisplayer
load: POSTWORLD
depend: [HolographicDisplays]
softdepend: [Multiverse-Core]
commands:
  observe:
    description: Create an observation
    usage: '/observe [text]'
  observations:
    description: Manage observations
    usage: '/observations'
